# Generated by Django 4.1.2 on 2022-10-23 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applib", options={"verbose_name": "Application"},
        ),
        migrations.AlterModelOptions(
            name="mastertaskholder",
            options={
                "verbose_name": "Master Task Holder",
                "verbose_name_plural": "Master Task Holder",
            },
        ),
        migrations.RemoveField(model_name="applib", name="subcat",),
    ]
