# Generated by Django 4.1.2 on 2022-10-23 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_applib_options_alter_mastertaskholder_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="mastertaskholder", name="applink",),
        migrations.RemoveField(model_name="mastertaskholder", name="subcat",),
    ]
