# Generated by Django 4.1.2 on 2022-10-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_mastertaskholder_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mastertaskholder",
            name="status",
            field=models.CharField(
                choices=[("C", "Completed"), ("P", "Pending")],
                default="P",
                max_length=2,
            ),
        ),
    ]
