# Generated by Django 4.1.2 on 2022-10-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_alter_applib_applink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applib",
            name="applink",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
